[keyboard]

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Alt"

[font]
size = 11

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"
